on: [push]

env: 
    path-to-file: "app/build/outputs/apk/release/app-release.apk"
jobs:
  kryptowire_analysis_job:
    runs-on: ubuntu-latest
    name: Build and submit app to Quokka
    steps:
      - uses: actions/checkout@v4

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      # Create APK Debug
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug

      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assemble

      - name: CSA Safe App Portal Analysis Submission
        uses: ./ # Uses an action in the root directory
        id: appSubmit
        with:
          path-to-file: ${{ env.path-to-file }}
          category: "PRODUCTIVITY"
          apiKey: ${{ secrets.SAP_API_KEY }}

